import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import Header from '@/components/Header';
import Image from 'next/image';
import pic from '@/public/img/pic.jpg';
import { FaAffiliatetheme } from 'react-icons/fa';
import { FcAndroidOs } from 'react-icons/fc';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Header />
				<h1>Main</h1>
				{/* IconContext.Provider 컴포넌트 임포트 후 웹 폰트 아이콘 활용한 부모요소에 wrapping 해주면 해당 컴포넌트 안쪽에서는 context api를 이용해서 동일한 스타일을 전역으로 활용 가능  */}
				{/* <IconContext.Provider value={{ color: 'blue', className: 'global-class-name' }}>
					<FaAffiliatetheme />
				</IconContext.Provider> */}

				{/* 직접적으로 웹폰트 아이콘에 커스텀 클래스명 , 사이즈 , 컬러값 지정 가능 */}
				<FaAffiliatetheme className='fontA' size='50' color='red' />
				<FcAndroidOs size='80' />

				{/* <div className={styles.pic}>
					<Image src={pic} alt='pic' fill quality={50} placeholder='blur' />
				</div>
				<div className={styles.pic}>
					<Image
						src='https://images.unsplash.com/photo-1690896855003-8c9dbbf87106?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80'
						alt='pic'
						fill
						quality={50}
					/>
				</div> */}
			</main>
		</>
	);
}
